import pygame

# --- Screen and Layout ---
SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 800
UI_PANEL_WIDTH = 250
SIM_WIDTH = SCREEN_WIDTH - UI_PANEL_WIDTH
SIM_HEIGHT = SCREEN_HEIGHT

# --- Grid ---
GRID_CELL_SIZE = 20
GRID_WIDTH = SIM_WIDTH // GRID_CELL_SIZE
GRID_HEIGHT = SIM_HEIGHT // GRID_CELL_SIZE

# --- Agent ---
AGENT_SIZE = 8 # Radius
AGENT_SPEED = 75
AGENT_MAX_FORCE = 190.0
AGENT_CAPACITY = 5
# Agent Roles (New)
ROLE_COLLECTOR = "COLLECTOR"
ROLE_BUILDER = "BUILDER"
AGENT_ROLES = [ROLE_COLLECTOR, ROLE_BUILDER]

# --- Resources & Base ---
RESOURCE_SIZE = 15
RESOURCE_MAX_QUANTITY = 50
RESOURCE_REGEN_RATE = 0.3
BASE_SIZE = 40
WATER_SOURCE_SIZE = 30 # New

# --- Building ---
BUILD_TIME = 2.5
BUILD_COST = 2

# --- Needs ---
# Energy/Hunger (Modified Decay)
MAX_ENERGY = 100
MAX_HUNGER = 100
ENERGY_DECAY_RATE_DAY = 1.5
ENERGY_DECAY_RATE_NIGHT = 2.5
HUNGER_INCREASE_RATE = 2.0
LOW_ENERGY_THRESHOLD = 30
HIGH_HUNGER_THRESHOLD = 70
EAT_AMOUNT = 60
REST_AMOUNT = 70 # Energy gain per rest action completion
EAT_TIME = 1.5
REST_TIME = 2.5 # Time for one rest action


# Thirst (New)
MAX_THIRST = 100
THIRST_INCREASE_RATE = 2.5 # Increases slightly faster than hunger?
HIGH_THIRST_THRESHOLD = 75
DRINK_AMOUNT = 70
DRINK_TIME = 1.0

# Sleepiness (New)
MAX_SLEEPINESS = 100
SLEEPINESS_INCREASE_RATE_AWAKE = 1.0 # How fast they get sleepy while awake
SLEEPINESS_DECREASE_RATE_ASLEEP = 15.0 # How fast sleepiness decreases *while sleeping*
HIGH_SLEEPINESS_THRESHOLD = 80
SLEEP_ENERGY_REGEN_RATE = 5.0 # Slow energy regen *while* sleeping action is active
# SLEEP_LOCATION_BONUS = 1.5 # Factor for faster sleepiness decrease at base (optional)

# Social (New)
MAX_SOCIAL = 100
SOCIAL_DECAY_RATE = 0.8 # Need decays slowly over time
LOW_SOCIAL_THRESHOLD = 30
SOCIAL_GAIN_RATE = 20.0 # How much social increases per interaction/tick
SOCIALIZE_TIME = 3.0 # Duration of a social interaction action
SOCIAL_INTERACTION_RANGE = GRID_CELL_SIZE * 3 # How close agents need to be to socialize

# Boredom (New)
MAX_BOREDOM = 100
BOREDOM_INCREASE_RATE_WORKING = 1.5 # Gets boring doing same task
BOREDOM_INCREASE_RATE_IDLE = 0.5   # Gets boring doing nothing
HIGH_BOREDOM_THRESHOLD = 70
BOREDOM_DECREASE_WHILE_LEISURE = 25.0 # How much boredom decreases during leisure action
LEISURE_TIME = 4.0 # Duration of leisure action

# Fear (New)
MAX_FEAR = 100
FEAR_INCREASE_PER_SECOND_NEAR_THREAT = 50.0 # How fast fear rises near threat
FEAR_DECAY_RATE = 5.0 # How fast fear decays when safe
HIGH_FEAR_THRESHOLD = 60
FLEE_SPEED_MULTIPLIER = 1.5 # Agents move faster when fleeing
THREAT_RADIUS = GRID_CELL_SIZE * 5 # How close agent needs to be to feel fear


# --- Environment Timing (New) ---
DAY_NIGHT_CYCLE_DURATION = 120 # Seconds for a full day-night cycle
DAY_DURATION_RATIO = 0.6 # 60% of cycle is day

# --- Simulation ---
FPS = 60
MAX_EVENT_LOG_MESSAGES = 15

# --- Colors ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255) # Collector color
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0) # Builder color
PURPLE = (128, 0, 128)
CYAN = (0, 255, 255)
GREY = (128, 128, 128)
DARK_GREY = (50, 50, 50)
LIGHT_GREY = (180, 180, 180)
OBSTACLE_COLOR = (80, 80, 80)
BASE_COLOR = (200, 200, 0)
# Night Overlay Color (New)
NIGHT_OVERLAY_COLOR = (0, 0, 30) # Dark blueish
MAX_NIGHT_ALPHA = 150 # Max transparency (0-255)
WATER_COLOR = (64, 164, 223) # New color for water
THREAT_COLOR = (200, 0, 100) # New color for threats (debug/minimap)

# --- UI Colors ---

UI_BG_COLOR = (30, 30, 50); BUTTON_COLOR = (80, 80, 110)
BUTTON_HOVER_COLOR = (110, 110, 140); BUTTON_TEXT_COLOR = WHITE
SELECTED_BUTTON_COLOR = (150, 150, 180); LOG_TEXT_COLOR = LIGHT_GREY
MINIMAP_BG_COLOR = (40, 40, 60); MINIMAP_BORDER_COLOR = WHITE
MINIMAP_AGENT_COLLECTOR_COLOR = BLUE; MINIMAP_AGENT_BUILDER_COLOR = ORANGE
MINIMAP_RESOURCE_COLOR = GREEN; MINIMAP_BASE_COLOR = YELLOW
MINIMAP_OBSTACLE_COLOR = DARK_GREY; MINIMAP_WATER_COLOR = WATER_COLOR # New
MINIMAP_THREAT_COLOR = THREAT_COLOR


# Minimap Colors (New)
MINIMAP_BG_COLOR = (40, 40, 60)
MINIMAP_BORDER_COLOR = WHITE
MINIMAP_AGENT_COLLECTOR_COLOR = BLUE
MINIMAP_AGENT_BUILDER_COLOR = ORANGE
MINIMAP_RESOURCE_COLOR = GREEN
MINIMAP_BASE_COLOR = YELLOW
MINIMAP_OBSTACLE_COLOR = DARK_GREY # Use existing obstacle color

# --- Agent States / Action Types (Unchanged) ---
STATE_IDLE = "IDLE"
STATE_MOVING_TO_RESOURCE = "MOVING_TO_RESOURCE"
STATE_MOVING_TO_BASE = "MOVING_TO_BASE"
STATE_MOVING_TO_BUILD = "MOVING_TO_BUILD"
STATE_MOVING_TO_WATER = "MOVING_TO_WATER" # New
STATE_MOVING_TO_SOCIAL_SPOT = "MOVING_TO_SOCIAL" # New (e.g., base)
STATE_SEEKING_LEISURE = "SEEKING_LEISURE" # New (e.g., wander near base)
STATE_WORKING = "WORKING"
STATE_FLEEING = "FLEEING" # New
STATE_SLEEPING = "SLEEPING" # New - distinct from RESTING action

ACTION_COLLECTING = "COLLECTING"
ACTION_RETURNING = "RETURNING" # Intent for MOVING_TO_BASE
ACTION_EATING = "EATING" # WORK action
ACTION_RESTING = "RESTING" # WORK action (brief energy boost)
ACTION_BUILDING = "BUILDING" # WORK action
ACTION_DRINKING = "DRINKING" # WORK action (New)
ACTION_SLEEPING_PREP = "SLEEP_PREP" # Intent for MOVING_TO_BASE/home
ACTION_SOCIALIZING = "SOCIALIZING" # WORK action (New)
ACTION_LEISURE = "LEISURE" # WORK action (New)

# --- Terrain Costs / Types (Unchanged) ---
TERRAIN_EMPTY = 0
TERRAIN_PLAINS = 1
TERRAIN_GRASS = 2
TERRAIN_MUD = 5
TERRAIN_WALL = 0
TERRAIN_WATER = 1
OBSTACLE_COST = TERRAIN_EMPTY

TERRAIN_TYPES = {
    "PLAINS": TERRAIN_PLAINS,
    "GRASS": TERRAIN_GRASS,
    "MUD": TERRAIN_MUD,
    "WALL": TERRAIN_WALL,
    "WATER": TERRAIN_WATER,
    "OBSTACLE": OBSTACLE_COLOR
}

TERRAIN_COLORS = {
    TERRAIN_EMPTY: (50, 50, 50),
    TERRAIN_PLAINS: (210, 180, 140),
    TERRAIN_GRASS: (34, 139, 34),
    TERRAIN_MUD: (139, 69, 19),
    TERRAIN_WALL: OBSTACLE_COLOR,
    TERRAIN_WATER: WATER_COLOR,
    OBSTACLE_COLOR: OBSTACLE_COLOR
}


# --- Quadtree (Unchanged) ---
QT_MAX_OBJECTS = 4
QT_MAX_LEVELS = 6

# --- UI Constants / Brushes ---
UI_PANEL_X = SIM_WIDTH
UI_FONT_SIZE_SMALL = 16
UI_FONT_SIZE_MEDIUM = 18
UI_FONT_SIZE_LARGE = 22
UI_LINE_HEIGHT = 20
BUTTON_HEIGHT = 28
BUTTON_PADDING = 5
# Minimap Size/Pos (New)
MINIMAP_WIDTH = UI_PANEL_WIDTH - 2 * BUTTON_PADDING
MINIMAP_HEIGHT = int(MINIMAP_WIDTH * (SIM_HEIGHT / SIM_WIDTH)) # Maintain aspect ratio
MINIMAP_X = UI_PANEL_X + BUTTON_PADDING
MINIMAP_Y = 50 # Position below control buttons

# Brush Types (Combined Tool/Paint/Spawn)
BRUSH_SELECT = "SELECT"
BRUSH_WALL = "PAINT_WALL"; BRUSH_PLAINS = "PAINT_PLAINS"
BRUSH_GRASS = "PAINT_GRASS"; BRUSH_MUD = "PAINT_MUD"
BRUSH_WATER = "PAINT_WATER" # New
BRUSH_CLEAR = "PAINT_CLEAR"
BRUSH_SPAWN_AGENT = "SPAWN_AGENT"; BRUSH_SPAWN_RESOURCE = "SPAWN_RESOURCE"
BRUSH_SPAWN_WATER = "SPAWN_WATER_SRC" # New (optional alternative to painting)
BRUSH_SPAWN_THREAT = "SPAWN_THREAT" # New
BRUSH_DELETE = "DELETE_ENTITY"


# Brush Groups (Unchanged)
PAINT_BRUSHES = [BRUSH_WALL, BRUSH_CLEAR, BRUSH_PLAINS, BRUSH_GRASS, BRUSH_MUD]
SPAWN_BRUSHES = [BRUSH_SPAWN_AGENT, BRUSH_SPAWN_RESOURCE]
TOOL_BRUSHES = [BRUSH_SELECT, BRUSH_DELETE]

MAX_BRUSH_SIZE = 5
MIN_BRUSH_SIZE = 1
