import pygame

# --- Screen and Layout ---
SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 800
UI_PANEL_WIDTH = 250
SIM_WIDTH = SCREEN_WIDTH - UI_PANEL_WIDTH
SIM_HEIGHT = SCREEN_HEIGHT

# --- Grid ---
GRID_CELL_SIZE = 20
GRID_WIDTH = SIM_WIDTH // GRID_CELL_SIZE
GRID_HEIGHT = SIM_HEIGHT // GRID_CELL_SIZE

# --- Agent ---
AGENT_SIZE = 8 # Radius
AGENT_SPEED = 75
AGENT_MAX_FORCE = 190.0
AGENT_CAPACITY = 5
# Agent Roles (New)
ROLE_COLLECTOR = "COLLECTOR"
ROLE_BUILDER = "BUILDER"
AGENT_ROLES = [ROLE_COLLECTOR, ROLE_BUILDER]

# --- Resources & Base ---
RESOURCE_SIZE = 15
RESOURCE_MAX_QUANTITY = 50
RESOURCE_REGEN_RATE = 0.3
BASE_SIZE = 40

# --- Building ---
BUILD_TIME = 2.5
BUILD_COST = 2

# --- Needs ---
MAX_ENERGY = 100
MAX_HUNGER = 100
ENERGY_DECAY_RATE_DAY = 1.5 # Base rate during day
ENERGY_DECAY_RATE_NIGHT = 2.5 # Increased rate during night
HUNGER_INCREASE_RATE = 2.0
LOW_ENERGY_THRESHOLD = 30
HIGH_HUNGER_THRESHOLD = 70
ENERGY_DECAY_RATE = 1.5
EAT_AMOUNT = 60
REST_AMOUNT = 70
EAT_TIME = 1.5
REST_TIME = 2.5

# --- Environment Timing (New) ---
DAY_NIGHT_CYCLE_DURATION = 120 # Seconds for a full day-night cycle
DAY_DURATION_RATIO = 0.6 # 60% of cycle is day

# --- Simulation ---
FPS = 60
MAX_EVENT_LOG_MESSAGES = 15

# --- Colors ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255) # Collector color
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0) # Builder color
PURPLE = (128, 0, 128)
CYAN = (0, 255, 255)
GREY = (128, 128, 128)
DARK_GREY = (50, 50, 50)
LIGHT_GREY = (180, 180, 180)
OBSTACLE_COLOR = (80, 80, 80)
BASE_COLOR = (200, 200, 0)
# Night Overlay Color (New)
NIGHT_OVERLAY_COLOR = (0, 0, 30) # Dark blueish
MAX_NIGHT_ALPHA = 150 # Max transparency (0-255)

# --- UI Colors ---
UI_BG_COLOR = (30, 30, 50)
BUTTON_COLOR = (80, 80, 110)
BUTTON_HOVER_COLOR = (110, 110, 140)
BUTTON_TEXT_COLOR = WHITE
SELECTED_BUTTON_COLOR = (150, 150, 180)
LOG_TEXT_COLOR = LIGHT_GREY
# Minimap Colors (New)
MINIMAP_BG_COLOR = (40, 40, 60)
MINIMAP_BORDER_COLOR = WHITE
MINIMAP_AGENT_COLLECTOR_COLOR = BLUE
MINIMAP_AGENT_BUILDER_COLOR = ORANGE
MINIMAP_RESOURCE_COLOR = GREEN
MINIMAP_BASE_COLOR = YELLOW
MINIMAP_OBSTACLE_COLOR = DARK_GREY # Use existing obstacle color

# --- Agent States / Action Types (Unchanged) ---
STATE_IDLE = "IDLE"
STATE_MOVING_TO_RESOURCE = "MOVING_TO_RESOURCE"
STATE_MOVING_TO_BASE = "MOVING_TO_BASE"
STATE_MOVING_TO_BUILD = "MOVING_TO_BUILD"
STATE_WORKING = "WORKING"

ACTION_COLLECTING = "COLLECTING"
ACTION_RETURNING = "RETURNING"
ACTION_EATING = "EATING"
ACTION_RESTING = "RESTING"
ACTION_BUILDING = "BUILDING"

# --- Terrain Costs / Types (Unchanged) ---
TERRAIN_EMPTY = 0
TERRAIN_PLAINS = 1
TERRAIN_GRASS = 2
TERRAIN_MUD = 5
TERRAIN_WALL = 0
OBSTACLE_COST = TERRAIN_EMPTY

TERRAIN_TYPES = {
    "PLAINS": TERRAIN_PLAINS,
    "GRASS": TERRAIN_GRASS,
    "MUD": TERRAIN_MUD,
    "WALL": TERRAIN_WALL,
    "OBSTACLE": OBSTACLE_COLOR
}

TERRAIN_COLORS = {
    TERRAIN_EMPTY: (50, 50, 50),
    TERRAIN_PLAINS: (210, 180, 140),
    TERRAIN_GRASS: (34, 139, 34),
    TERRAIN_MUD: (139, 69, 19),
    TERRAIN_WALL: OBSTACLE_COLOR,
    OBSTACLE_COLOR: OBSTACLE_COLOR
}


# --- Quadtree (Unchanged) ---
QT_MAX_OBJECTS = 4
QT_MAX_LEVELS = 6

# --- UI Constants / Brushes ---
UI_PANEL_X = SIM_WIDTH
UI_FONT_SIZE_SMALL = 16
UI_FONT_SIZE_MEDIUM = 18
UI_FONT_SIZE_LARGE = 22
UI_LINE_HEIGHT = 20
BUTTON_HEIGHT = 28
BUTTON_PADDING = 5
# Minimap Size/Pos (New)
MINIMAP_WIDTH = UI_PANEL_WIDTH - 2 * BUTTON_PADDING
MINIMAP_HEIGHT = int(MINIMAP_WIDTH * (SIM_HEIGHT / SIM_WIDTH)) # Maintain aspect ratio
MINIMAP_X = UI_PANEL_X + BUTTON_PADDING
MINIMAP_Y = 50 # Position below control buttons

# Brush Types (Combined Tool/Paint/Spawn)
BRUSH_SELECT = "SELECT"
BRUSH_WALL = "PAINT_WALL"
BRUSH_PLAINS = "PAINT_PLAINS"
BRUSH_GRASS = "PAINT_GRASS"
BRUSH_MUD = "PAINT_MUD"
BRUSH_CLEAR = "PAINT_CLEAR" # Essentially paints plains
BRUSH_SPAWN_AGENT = "SPAWN_AGENT"
BRUSH_SPAWN_RESOURCE = "SPAWN_RESOURCE"
BRUSH_DELETE = "DELETE_ENTITY" # Added delete brush


# Brush Groups (Unchanged)
PAINT_BRUSHES = [BRUSH_WALL, BRUSH_CLEAR, BRUSH_PLAINS, BRUSH_GRASS, BRUSH_MUD]
SPAWN_BRUSHES = [BRUSH_SPAWN_AGENT, BRUSH_SPAWN_RESOURCE]
TOOL_BRUSHES = [BRUSH_SELECT, BRUSH_DELETE]

MAX_BRUSH_SIZE = 5
MIN_BRUSH_SIZE = 1
